# Generated by Django 5.0 on 2024-01-27 08:30

import UserHome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHome', '0005_remove_otpmodel_user_otpmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=150, validators=[UserHome.models.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=150, validators=[UserHome.models.validate_name], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[UserHome.models.validate_phone]),
        ),
    ]
