# Generated by Django 5.0 on 2024-02-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHome', '0007_userprofile_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_code',
        ),
    ]
