# Generated by Django 5.0 on 2024-02-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHome', '0009_refferal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refferal',
        ),
    ]
