# Generated by Django 5.0 on 2024-02-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHome', '0010_delete_refferal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
