# Generated by Django 5.0 on 2024-01-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminHome', '0002_dailysales'),
        ('admin_product_management', '0011_alter_product_price_alter_productvariant_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysales',
            old_name='sales',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='dailysales',
            name='product',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='admin_product_management.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysales',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
