# Generated by Django 5.0 on 2024-01-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
