# Generated by Django 5.0 on 2024-01-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0005_alter_product_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_product_management.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='outer_material',
            field=models.CharField(),
        ),
    ]
