# Generated by Django 5.0 on 2024-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0006_remove_product_discounted_price_alter_offer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
