# Generated by Django 5.0 on 2024-01-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0007_offer_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_product_management.product'),
        ),
    ]
