# Generated by Django 5.0 on 2024-01-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0008_alter_offer_product'),
        ('user_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_varient',
            new_name='ProductVariant',
        ),
    ]
