# Generated by Django 5.0 on 2024-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0012_coupon_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
