# Generated by Django 5.0 on 2024-02-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0014_coupon_description_alter_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_amount',
            new_name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
    ]
