# Generated by Django 4.2.7 on 2024-02-09 06:35

import admin_product_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_management', '0016_alter_usercoupon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.IntegerField(validators=[admin_product_management.models.validate_percent]),
        ),
    ]
