# Generated by Django 5.0 on 2024-01-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0002_rename_product_varient_cartitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
