# Generated by Django 5.0 on 2024-01-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0003_alter_cart_total_amount_alter_cartitem_sub_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-id']},
        ),
    ]
