# Generated by Django 5.0 on 2024-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='is_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
