# Generated by Django 5.0 on 2024-01-27 12:11

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_useraddresses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='pincode',
            field=models.CharField(max_length=150, validators=[user_profile.models.validate_pin], verbose_name='first name'),
        ),
    ]
