# Generated by Django 5.0 on 2024-01-29 08:34

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_useraddresses_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='pincode',
            field=models.CharField(max_length=6, validators=[user_profile.models.validate_pin]),
        ),
    ]
