# Generated by Django 5.0 on 2024-02-05 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_rename_redeemed_refferal_is_redeemed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refferal',
            new_name='Referral',
        ),
    ]
