# Generated by Django 5.0 on 2024-02-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycharge',
            old_name='place',
            new_name='city',
        ),
    ]
