# Generated by Django 5.0 on 2024-02-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_order', '0002_rename_place_deliverycharge_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycharge',
            old_name='charge',
            new_name='amount',
        ),
    ]
