# Generated by Django 5.0 on 2024-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_varient',
            new_name='product_variant',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
