# Generated by Django 5.0 on 2024-01-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0002_rename_product_varient_orderitem_product_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
