# Generated by Django 5.0 on 2024-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0003_rename_status_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
