# Generated by Django 5.0 on 2024-01-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0005_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(default='warning', max_length=50),
        ),
    ]
