# Generated by Django 5.0 on 2024-01-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0006_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_listed',
            field=models.BooleanField(default='True'),
        ),
    ]
