# Generated by Django 5.0 on 2024-01-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0007_orderstatus_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
