# Generated by Django 5.0 on 2024-01-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0009_alter_orderstatus_color_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderaddress',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.IntegerField(default=1234567, max_length=50),
            preserve_default=False,
        ),
    ]
