# Generated by Django 5.0 on 2024-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0011_alter_orderitem_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_id',
            field=models.IntegerField(default=1),
        ),
    ]
