# Generated by Django 5.0 on 2024-02-01 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0015_remove_orderitem_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
    ]
