# Generated by Django 5.0 on 2024-02-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0018_wallet_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
