# Generated by Django 5.0 on 2024-02-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0020_coupon_usercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
