# Generated by Django 5.0 on 2024-02-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0021_remove_usercoupon_coupon_remove_usercoupon_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
