# Generated by Django 5.0 on 2024-02-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0022_deliverycharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCharge',
        ),
    ]
